### PR TITLE
Mobile view 

### PR DESCRIPTION
**Pull request by uno36**
this is the portfolio project milestone 1
I created a mobile-first view of the portfolio
I configured linters and managed to check for errors before submission
I also made changes to the readme file

### CODE REVIEW

**Review by franclobo — COMMENTED** [review]
Hi @uno36, 

terminator

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional README file, all the main headers must be completed, please complete your project's description 

description-project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by topeogunleye — COMMENTED** [review]
Hi @uno36, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a project, that doesn't have a descriptive title and summary, kindly add one. See a demo on how to add a PR description below:

pull_request_desc
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

**Comment by uno36** [comment]
this is the portfolio project milestone 1
I created a mobile-first view of the portfolio
I configured linters and managed to check for errors before submission 
I also made changes to the readme file

**Comment by topeogunleye** [comment]
> this is the portfolio project milestone 1 I created a mobile-first view of the portfolio I configured linters and managed to check for errors before submission I also made changes to the readme file

Kindly edit  your PR Description to add it:

image

**Comment by didierganthier** [comment]
> > this is the portfolio project milestone 1 I created a mobile-first view of the portfolio I configured linters and managed to check for errors before submission I also made changes to the readme file
> 
> Kindly edit your PR Description to add it:
> 
> image

@uno36

**Review by didierganthier — CHANGES_REQUESTED** [review]
Hi @uno36 ,

🎉 Good job so far! You're making great progress on this project, but there are still a few areas that need attention before we can move on to the next step.



## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct GitHub flow ✔️ 

## Required Changes 🛠
- [ ] Well done on the project overall 👍🏽 but make sure to get the files relevant to this project in this PR so the reviewers can add inline comments to point out the issues better. ❗ 
- [ ] Nice works section 💯  but in order to improve the CSS and make it easier to have the page responsive later on, the main container of the projects should have a `display: grid`
- [ ] In order to use more semantic tags, the technology categories ("Languages", "Frameworks" and "Skills") are in a `ul`, each of them in a `li` 🤓 
- [ ] The image here in this `section` should be part of the background and not included as an image positioned towards the element, this could mess up the design therefore the section should have the proper background image (decorations are always backgrounded images, not `img` tags)

- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

**Pull request merged**
